### CREATE SHEET
POST http://localhost:3000/sheet
method: "POST"
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc3MTUwNTcxMywiZXhwIjoxNzcxNTE2NTEzfQ.aci9ARk_kcB5OBkOYdVqbRarVcRK7gglTX-paCCzQ_c

{
    "name":"Job été 2026"
}

### GET ALL SHEETS
GET http://localhost:3000/sheet
method: "GET"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc3MTUwNTcxMywiZXhwIjoxNzcxNTE2NTEzfQ.aci9ARk_kcB5OBkOYdVqbRarVcRK7gglTX-paCCzQ_c

### GET SHEET'S INFOS
GET http://localhost:3000/sheet/Job%20%C3%A9t%C3%A9%202026
method: "GET"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc3MTUwNTcxMywiZXhwIjoxNzcxNTE2NTEzfQ.aci9ARk_kcB5OBkOYdVqbRarVcRK7gglTX-paCCzQ_c
